<?php
/**
 * Demo section: a "Product resources" section with a Downloads dropdown.
 *
 * Demo content for the local test site (rendered by playground/blueprint.json),
 * not part of the plugin: block markup exported from the editor.
 *
 * @package Thingamablocks
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!-- wp:generateblocks/element {"uniqueId":"ebcc725f","tagName":"section","styles":{"display":"flex","flexDirection":"column","alignItems":"flex-start","rowGap":"0.75rem","paddingTop":"2rem","paddingRight":"2rem","paddingBottom":"2rem","paddingLeft":"2rem","borderTopLeftRadius":"0.75rem","borderTopRightRadius":"0.75rem","borderBottomRightRadius":"0.75rem","borderBottomLeftRadius":"0.75rem","backgroundColor":"var(\u002d\u002dbase-2, #f7f8f9)"},"css":".gb-element-ebcc725f{align-items:flex-start;background-color:var(\u002d\u002dbase-2,#f7f8f9);display:flex;flex-direction:column;row-gap:0.75rem;border-radius:0.75rem;padding:2rem}","htmlAttributes":{"aria-labelledby":"product-resources"}} -->
<section class="gb-element-ebcc725f" aria-labelledby="product-resources"><!-- wp:generateblocks/text {"uniqueId":"fbdecdbc","tagName":"h2","styles":{"marginBottom":"0","fontSize":"1.5rem"},"css":".gb-text-fbdecdbc{font-size:1.5rem;margin-bottom:0}","htmlAttributes":{"id":"product-resources"}} -->
<h2 class="gb-text gb-text-fbdecdbc" id="product-resources"><?php echo esc_html__( 'Product resources', 'thingamablocks' ); ?></h2>
<!-- /wp:generateblocks/text -->

<!-- wp:generateblocks/text {"uniqueId":"3b3bd5ea","tagName":"p","styles":{"marginBottom":"0.5rem","color":"var(\u002d\u002dcontrast-2, #575760)"},"css":".gb-text-3b3bd5ea{color:var(\u002d\u002dcontrast-2,#575760);margin-bottom:0.5rem}"} -->
<p class="gb-text gb-text-3b3bd5ea"><?php echo esc_html__( 'Brochures, price lists and brand assets, ready to download.', 'thingamablocks' ); ?></p>
<!-- /wp:generateblocks/text -->

<!-- wp:thingamablocks/dropdown -->
<!-- wp:generateblocks/text {"uniqueId":"d238549b","tagName":"button","styles":{"display":"inline-flex","alignItems":"center","justifyContent":"space-between","columnGap":"0.75rem","paddingTop":"0.75rem","paddingRight":"1.25rem","paddingBottom":"0.75rem","paddingLeft":"1.25rem","borderTopLeftRadius":"0.5rem","borderTopRightRadius":"0.5rem","borderBottomRightRadius":"0.5rem","borderBottomLeftRadius":"0.5rem","borderTopWidth":"0","borderRightWidth":"0","borderBottomWidth":"0","borderLeftWidth":"0","borderTopStyle":"none","borderRightStyle":"none","borderBottomStyle":"none","borderLeftStyle":"none","borderTopColor":"transparent","borderRightColor":"transparent","borderBottomColor":"transparent","borderLeftColor":"transparent","backgroundColor":"var(\u002d\u002daccent, #1e73be)","color":"var(\u002d\u002dbase-3, #ffffff)","fontSize":"1rem","fontWeight":"600","lineHeight":"1.2","cursor":"pointer","transition":"background-color 0.2s ease","\u0026:is(:hover, :focus-visible), \u0026[aria-expanded=\u0022true\u0022]":{"backgroundColor":"var(\u002d\u002dcontrast, #222222)","color":"var(\u002d\u002dbase-3, #ffffff)"},"\u0026:focus-visible":{"outlineWidth":"2px","outlineStyle":"solid","outlineColor":"var(\u002d\u002daccent, #1e73be)","outlineOffset":"2px"},".gb-shape svg":{"width":"1.1em","height":"1.1em","transition":"transform 0.2s ease"},"\u0026[aria-expanded=\u0022true\u0022] .gb-shape svg":{"transform":"rotate(180deg)"}},"css":".gb-text-d238549b{align-items:center;background-color:var(\u002d\u002daccent,#1e73be);color:var(\u002d\u002dbase-3,#ffffff);column-gap:0.75rem;cursor:pointer;display:inline-flex;font-size:1rem;font-weight:600;justify-content:space-between;line-height:1.2;transition:background-color 0.2s ease;border:0 none transparent;border-radius:0.5rem;padding:0.75rem 1.25rem}.gb-text-d238549b:focus-visible{outline-color:var(\u002d\u002daccent,#1e73be);outline-offset:2px;outline-style:solid;outline-width:2px}.gb-text-d238549b:is(:hover,:focus-visible),.gb-text-d238549b[aria-expanded=\u0022true\u0022]{background-color:var(\u002d\u002dcontrast,#222222);color:var(\u002d\u002dbase-3,#ffffff)}.gb-text-d238549b[aria-expanded=\u0022true\u0022] .gb-shape svg{transform:rotate(180deg)}.gb-text-d238549b .gb-shape svg{height:1.1em;transition:transform 0.2s ease;width:1.1em}","htmlAttributes":{"data-dropdown-part":"button"},"iconLocation":"after"} -->
<button class="gb-text-d238549b" data-dropdown-part="button"><span class="gb-text"><?php echo esc_html__( 'Downloads', 'thingamablocks' ); ?></span><span class="gb-shape"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"></path></svg></span></button>
<!-- /wp:generateblocks/text -->

<!-- wp:generateblocks/element {"uniqueId":"c1eaa403","tagName":"ul","styles":{"display":"flex","flexDirection":"column","rowGap":"0.125rem","marginTop":"0","marginRight":"0","marginBottom":"0","marginLeft":"0","paddingTop":"0.375rem","paddingRight":"0.375rem","paddingBottom":"0.375rem","paddingLeft":"0.375rem","borderTopLeftRadius":"0.5rem","borderTopRightRadius":"0.5rem","borderBottomRightRadius":"0.5rem","borderBottomLeftRadius":"0.5rem","borderTopWidth":"1px","borderRightWidth":"1px","borderBottomWidth":"1px","borderLeftWidth":"1px","borderTopStyle":"solid","borderRightStyle":"solid","borderBottomStyle":"solid","borderLeftStyle":"solid","borderTopColor":"var(\u002d\u002dbase, #f0f0f0)","borderRightColor":"var(\u002d\u002dbase, #f0f0f0)","borderBottomColor":"var(\u002d\u002dbase, #f0f0f0)","borderLeftColor":"var(\u002d\u002dbase, #f0f0f0)","backgroundColor":"var(\u002d\u002dbase-3, #ffffff)","color":"var(\u002d\u002dcontrast, #222222)","boxShadow":"0 12px 32px -12px rgba(0, 0, 0, 0.25), 0 2px 6px rgba(0, 0, 0, 0.06)","listStyleType":"none"},"css":".gb-element-c1eaa403{background-color:var(\u002d\u002dbase-3,#ffffff);box-shadow:0 12px 32px -12px rgba(0,0,0,0.25),0 2px 6px rgba(0,0,0,0.06);color:var(\u002d\u002dcontrast,#222222);display:flex;flex-direction:column;list-style-type:none;row-gap:0.125rem;border:1px solid var(\u002d\u002dbase,#f0f0f0);border-radius:0.5rem;margin:0;padding:0.375rem}","htmlAttributes":{"data-dropdown-part":"drawer"}} -->
<ul class="gb-element-c1eaa403" data-dropdown-part="drawer"><!-- wp:generateblocks/element {"uniqueId":"0d3602e1","tagName":"li","styles":{"marginTop":"0","marginRight":"0","marginBottom":"0","marginLeft":"0"},"css":".gb-element-0d3602e1{margin:0}"} -->
<li class="gb-element-0d3602e1"><!-- wp:generateblocks/element {"uniqueId":"475faffe","tagName":"a","styles":{"display":"flex","flexDirection":"column","rowGap":"0.125rem","paddingTop":"0.5rem","paddingRight":"0.75rem","paddingBottom":"0.5rem","paddingLeft":"0.75rem","borderTopLeftRadius":"0.25rem","borderTopRightRadius":"0.25rem","borderBottomRightRadius":"0.25rem","borderBottomLeftRadius":"0.25rem","color":"var(\u002d\u002dcontrast, #222222)","textDecoration":"none","transition":"background-color 0.15s ease","\u0026:is(:hover, :focus-visible)":{"backgroundColor":"var(\u002d\u002dbase-2, #f7f8f9)","color":"var(\u002d\u002daccent, #1e73be)"},"\u0026:focus-visible":{"outlineWidth":"2px","outlineStyle":"solid","outlineColor":"var(\u002d\u002daccent, #1e73be)","outlineOffset":"-2px"}},"css":".gb-element-475faffe{color:var(\u002d\u002dcontrast,#222222);display:flex;flex-direction:column;row-gap:0.125rem;text-decoration:none;transition:background-color 0.15s ease;border-radius:0.25rem;padding:0.5rem 0.75rem}.gb-element-475faffe:focus-visible{outline-color:var(\u002d\u002daccent,#1e73be);outline-offset:-2px;outline-style:solid;outline-width:2px}.gb-element-475faffe:is(:hover,:focus-visible){background-color:var(\u002d\u002dbase-2,#f7f8f9);color:var(\u002d\u002daccent,#1e73be)}","htmlAttributes":{"href":"#"}} -->
<a class="gb-element-475faffe" href="#"><!-- wp:generateblocks/text {"uniqueId":"25e6eb95","tagName":"span","styles":{"fontSize":"0.9375rem","fontWeight":"600","lineHeight":"1.3"},"css":".gb-text-25e6eb95{font-size:0.9375rem;font-weight:600;line-height:1.3}"} -->
<span class="gb-text gb-text-25e6eb95"><?php echo esc_html__( 'Brochure', 'thingamablocks' ); ?></span>
<!-- /wp:generateblocks/text -->

<!-- wp:generateblocks/text {"uniqueId":"1dffaefe","tagName":"span","styles":{"fontSize":"0.8125rem","lineHeight":"1.3","color":"var(\u002d\u002dcontrast-2, #575760)"},"css":".gb-text-1dffaefe{color:var(\u002d\u002dcontrast-2,#575760);font-size:0.8125rem;line-height:1.3}"} -->
<span class="gb-text gb-text-1dffaefe"><?php echo esc_html__( 'PDF · 2.4 MB', 'thingamablocks' ); ?></span>
<!-- /wp:generateblocks/text --></a>
<!-- /wp:generateblocks/element --></li>
<!-- /wp:generateblocks/element -->

<!-- wp:generateblocks/element {"uniqueId":"a5f4d34e","tagName":"li","styles":{"marginTop":"0","marginRight":"0","marginBottom":"0","marginLeft":"0"},"css":".gb-element-a5f4d34e{margin:0}"} -->
<li class="gb-element-a5f4d34e"><!-- wp:generateblocks/element {"uniqueId":"cf4e4cf0","tagName":"a","styles":{"display":"flex","flexDirection":"column","rowGap":"0.125rem","paddingTop":"0.5rem","paddingRight":"0.75rem","paddingBottom":"0.5rem","paddingLeft":"0.75rem","borderTopLeftRadius":"0.25rem","borderTopRightRadius":"0.25rem","borderBottomRightRadius":"0.25rem","borderBottomLeftRadius":"0.25rem","color":"var(\u002d\u002dcontrast, #222222)","textDecoration":"none","transition":"background-color 0.15s ease","\u0026:is(:hover, :focus-visible)":{"backgroundColor":"var(\u002d\u002dbase-2, #f7f8f9)","color":"var(\u002d\u002daccent, #1e73be)"},"\u0026:focus-visible":{"outlineWidth":"2px","outlineStyle":"solid","outlineColor":"var(\u002d\u002daccent, #1e73be)","outlineOffset":"-2px"}},"css":".gb-element-cf4e4cf0{color:var(\u002d\u002dcontrast,#222222);display:flex;flex-direction:column;row-gap:0.125rem;text-decoration:none;transition:background-color 0.15s ease;border-radius:0.25rem;padding:0.5rem 0.75rem}.gb-element-cf4e4cf0:focus-visible{outline-color:var(\u002d\u002daccent,#1e73be);outline-offset:-2px;outline-style:solid;outline-width:2px}.gb-element-cf4e4cf0:is(:hover,:focus-visible){background-color:var(\u002d\u002dbase-2,#f7f8f9);color:var(\u002d\u002daccent,#1e73be)}","htmlAttributes":{"href":"#"}} -->
<a class="gb-element-cf4e4cf0" href="#"><!-- wp:generateblocks/text {"uniqueId":"4ca72b83","tagName":"span","styles":{"fontSize":"0.9375rem","fontWeight":"600","lineHeight":"1.3"},"css":".gb-text-4ca72b83{font-size:0.9375rem;font-weight:600;line-height:1.3}"} -->
<span class="gb-text gb-text-4ca72b83"><?php echo esc_html__( 'Price list', 'thingamablocks' ); ?></span>
<!-- /wp:generateblocks/text -->

<!-- wp:generateblocks/text {"uniqueId":"cf50d8f4","tagName":"span","styles":{"fontSize":"0.8125rem","lineHeight":"1.3","color":"var(\u002d\u002dcontrast-2, #575760)"},"css":".gb-text-cf50d8f4{color:var(\u002d\u002dcontrast-2,#575760);font-size:0.8125rem;line-height:1.3}"} -->
<span class="gb-text gb-text-cf50d8f4"><?php echo esc_html__( 'XLSX · 48 KB', 'thingamablocks' ); ?></span>
<!-- /wp:generateblocks/text --></a>
<!-- /wp:generateblocks/element --></li>
<!-- /wp:generateblocks/element -->

<!-- wp:generateblocks/element {"uniqueId":"371a61ed","tagName":"li","styles":{"marginTop":"0","marginRight":"0","marginBottom":"0","marginLeft":"0"},"css":".gb-element-371a61ed{margin:0}"} -->
<li class="gb-element-371a61ed"><!-- wp:generateblocks/element {"uniqueId":"a1b9fc09","tagName":"a","styles":{"display":"flex","flexDirection":"column","rowGap":"0.125rem","paddingTop":"0.5rem","paddingRight":"0.75rem","paddingBottom":"0.5rem","paddingLeft":"0.75rem","borderTopLeftRadius":"0.25rem","borderTopRightRadius":"0.25rem","borderBottomRightRadius":"0.25rem","borderBottomLeftRadius":"0.25rem","color":"var(\u002d\u002dcontrast, #222222)","textDecoration":"none","transition":"background-color 0.15s ease","\u0026:is(:hover, :focus-visible)":{"backgroundColor":"var(\u002d\u002dbase-2, #f7f8f9)","color":"var(\u002d\u002daccent, #1e73be)"},"\u0026:focus-visible":{"outlineWidth":"2px","outlineStyle":"solid","outlineColor":"var(\u002d\u002daccent, #1e73be)","outlineOffset":"-2px"}},"css":".gb-element-a1b9fc09{color:var(\u002d\u002dcontrast,#222222);display:flex;flex-direction:column;row-gap:0.125rem;text-decoration:none;transition:background-color 0.15s ease;border-radius:0.25rem;padding:0.5rem 0.75rem}.gb-element-a1b9fc09:focus-visible{outline-color:var(\u002d\u002daccent,#1e73be);outline-offset:-2px;outline-style:solid;outline-width:2px}.gb-element-a1b9fc09:is(:hover,:focus-visible){background-color:var(\u002d\u002dbase-2,#f7f8f9);color:var(\u002d\u002daccent,#1e73be)}","htmlAttributes":{"href":"#"}} -->
<a class="gb-element-a1b9fc09" href="#"><!-- wp:generateblocks/text {"uniqueId":"eea0cd3d","tagName":"span","styles":{"fontSize":"0.9375rem","fontWeight":"600","lineHeight":"1.3"},"css":".gb-text-eea0cd3d{font-size:0.9375rem;font-weight:600;line-height:1.3}"} -->
<span class="gb-text gb-text-eea0cd3d"><?php echo esc_html__( 'Logo pack', 'thingamablocks' ); ?></span>
<!-- /wp:generateblocks/text -->

<!-- wp:generateblocks/text {"uniqueId":"e1891d9a","tagName":"span","styles":{"fontSize":"0.8125rem","lineHeight":"1.3","color":"var(\u002d\u002dcontrast-2, #575760)"},"css":".gb-text-e1891d9a{color:var(\u002d\u002dcontrast-2,#575760);font-size:0.8125rem;line-height:1.3}"} -->
<span class="gb-text gb-text-e1891d9a"><?php echo esc_html__( 'ZIP · 6.1 MB', 'thingamablocks' ); ?></span>
<!-- /wp:generateblocks/text --></a>
<!-- /wp:generateblocks/element --></li>
<!-- /wp:generateblocks/element --></ul>
<!-- /wp:generateblocks/element -->
<!-- /wp:thingamablocks/dropdown --></section>
<!-- /wp:generateblocks/element -->
